CREATE TABLE TEMPERATURES(
    DATE_TEMP DATE,
    DEP_ID VARCHAR(3) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    MIN_TEMP DECIMAL,
    MAX_TEMP DECIMAL,
    MEAN_TEMP DECIMAL,

    PRIMARY KEY (DEP_ID, DEPARTMENT),
    FOREIGN KEY (DEP_ID) REFERENCES PROJET_DEP(codeD)
);