
-- Exo 4.1
-- Created and Imported the Table of DEPARTMENTS into my DB
CREATE TABLE DEPARTMENTS(
  ID VARCHAR(5) NOT NULL,
  NOM_DEP VARCHAR(50) NOT NULL,
  NUM_ARRONDISSEMENTS INT,
  NUM_CANTONS INT,
  NUM_COMMUNES INT,
  POPULATION INT,
  PRIMARY KEY (ID, NOM_DEP)
);